[package]
name = "rust-high"
version = "0.1.0"
authors = ["mikael"]

[dependencies]
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
toml = "^0.4"
reqwest = "^0.8"
clap = "^2.0"
itertools = "^0.7"
error-chain = "^0.11"
